// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viora.Infrastructure;

#nullable disable

namespace Viora.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Viora.Domain.Orders.AddonOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AddonOrders", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Orders.SubscriptionOrder", b =>
            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                }
                )
            );

            modelBuilder.Entity("Viora.Domain.MedicalRecords.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubscriptionOrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionOrder");
                });

            modelBuilder.Entity("Viora.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Viora.Domain.Plans.Features.Feature", b =>
            { 
                    b.Property<long>("BloodGlucose")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("HeartRate")
                        .HasColumnType("bigint");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("MedicalRecords", (string)null);
            }
        );

            modelBuilder.Entity("Viora.Domain.Organizations.OrganizationHistory.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Plans.Features.FeatureUsage", b =>
                { 
                    b.HasKey("Id");

                    b.ToTable("Organization");
                }
            );

            modelBuilder.Entity("Viora.Domain.Organizations.OrganizationHistory.OrganizationVisits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LimitedFeatureId");
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("FeatureUsages", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Plans.Features.LimitedFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Limit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LimitedFeatures", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name");
                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationVisits", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Users.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MedicalRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Users.Identity.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlanPeriod")
                        .HasColumnType("int")
                        .HasColumnName("PlanPeriodId");

                    b.Property<double>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Plans.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LimitedFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("LimitedFeatureId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.Addons.AddonOrderLimitedFeature", b =>
                {
                    b.Property<Guid>("AddonOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LimitedFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AddonOrderId", "LimitedFeatureId");

                    b.ToTable("AddonOrderLimitedFeatures", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.Addons.LimitedFeatureAddon", b =>
                { 
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("AuthIdentities", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Users.Identity.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "users:read"
                        });
                });

            modelBuilder.Entity("Viora.Domain.Users.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Registered"
                        });
                });

            modelBuilder.Entity("Viora.Domain.Users.Identity.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        });
                });

            modelBuilder.Entity("Viora.Domain.Users.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddonOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddonType")
                        .HasColumnType("int");

                    b.Property<Guid>("LimitedFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<int>("RestoreValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddonOrderId");

                    b.HasIndex("LimitedFeatureId");

                    b.ToTable("LimitedFeatureAddons", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubscriptionsEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubscriptionsStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PlanId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.SubscriptionAddon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LimitedFeatureAddonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LimitedFeatureAddonId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionAddon");
                });

            modelBuilder.Entity("Viora.Domain.Plans.Features.FeatureUsage", b =>
                {
                    b.HasOne("Viora.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viora.Domain.Plans.PlanFeature", b =>
                {
                    b.HasOne("Viora.Domain.Plans.Features.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId");

                    b.HasOne("Viora.Domain.Plans.Features.LimitedFeature", null)
                        .WithMany()
                        .HasForeignKey("LimitedFeatureId");

                    b.HasOne("Viora.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.Addons.AddonOrderLimitedFeature", b =>
                {
                    b.HasOne("Viora.Domain.Orders.AddonOrder", null)
                        .WithMany()
                        .HasForeignKey("AddonOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.Addons.LimitedFeatureAddon", b =>
                {
                    b.HasOne("Viora.Domain.Orders.AddonOrder", null)
                        .WithMany("Addons")
                        .HasForeignKey("AddonOrderId");

                    b.HasOne("Viora.Domain.Plans.Features.LimitedFeature", null)
                        .WithMany()
                        .HasForeignKey("LimitedFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.Subscription", b =>
                {
                    b.HasOne("Viora.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viora.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Viora.Domain.Users.Owners.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BecameOwnerAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NationalityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Owners", (string)null);
                });

            modelBuilder.Entity("Viora.Infrastructure.Authentication.LocalCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HashVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastChangedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("LocalCredential");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("Viora.Domain.Users.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viora.Domain.Users.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viora.Domain.MedicalRecords.MedicalRecord", b =>
                {
                    b.HasOne("Viora.Domain.Users.Customers.Customer", "Customer")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Viora.Domain.MedicalRecords.MedicalRecord", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Viora.Domain.MedicalRecords.Internal.Allergy", "Allergies", b1 =>
                        {
                            b1.Property<Guid>("MedicalRecordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Allergy");

                            b1.HasKey("MedicalRecordId", "Value");

                            b1.ToTable("MedicalRecordAllergies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicalRecordId");
                        });

                    b.OwnsOne("Viora.Domain.MedicalRecords.Internal.BloodPressure", "BloodPressure", b1 =>
                        {
                            b1.Property<Guid>("MedicalRecordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("Diastolic")
                                .HasColumnType("bigint")
                                .HasColumnName("BloodPressureDiastolic");

                            b1.Property<long>("Systolic")
                                .HasColumnType("bigint")
                                .HasColumnName("BloodPressureSystolic");

                            b1.HasKey("MedicalRecordId");

                            b1.ToTable("MedicalRecords");

                            b1.WithOwner()
                                .HasForeignKey("MedicalRecordId");
                        });

                    b.Navigation("Allergies");

                    b.Navigation("BloodPressure")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Viora.Domain.Organizations.OrganizationHistory.OrganizationVisits", b =>
                {
                    b.HasOne("Viora.Domain.Users.Customers.Customer", "Customer")
                        .WithMany("OrganizationVisits")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viora.Domain.Organizations.OrganizationHistory.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Viora.Domain.Users.Customers.Customer", b =>
                {
                    b.HasOne("Viora.Domain.Users.Identity.User", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Viora.Domain.Users.Customers.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Viora.Domain.Shared.Contact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("CustomerId", "Id");

                            b1.ToTable("Contact");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("Viora.Domain.Users.Internal.PersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Contacts");

                    b.Navigation("PersonalInfo")
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Viora.Domain.Users.Identity.AuthIdentity", b =>
                {
                    b.HasOne("Viora.Domain.Users.Identity.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viora.Domain.Users.Identity.RolePermission", b =>
                {
                    b.HasOne("Viora.Domain.Users.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viora.Domain.Users.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.SubscriptionAddon", b =>
                {
                    b.HasOne("Viora.Domain.Subscriptions.Addons.LimitedFeatureAddon", "LimitedFeatureAddon")
                        .WithMany()
                        .HasForeignKey("LimitedFeatureAddonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viora.Domain.Subscriptions.Subscription", "Subscription")
                        .WithMany("Addons")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LimitedFeatureAddon");

                    b.Navigation("Subscription");
                });

                modelBuilder.Entity("Viora.Domain.Orders.AddonOrder", b =>
                {
                    b.Navigation("Addons");
                });

            modelBuilder.Entity("Viora.Domain.Subscriptions.Subscription", b =>
                {
                    b.Navigation("Addons");
                    modelBuilder.Entity("Viora.Domain.Users.Identity.User", b =>
                        {
                            b.OwnsOne("Viora.Domain.Users.Internal.PersonalInfo", "PersonalInfo", b1 =>
                                {
                                    b1.Property<Guid>("UserId")
                                        .HasColumnType("uniqueidentifier");

                                    b1.Property<DateOnly>("DateOfBirth")
                                        .HasColumnType("date");

                                    b1.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b1.Property<string>("Gender")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b1.Property<string>("LastName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b1.HasKey("UserId");

                                    b1.ToTable("Users");

                                    b1.WithOwner()
                                        .HasForeignKey("UserId");
                                });
                            b.Navigation("PersonalInfo")
                                .IsRequired();


                        });
             });
                    modelBuilder.Entity("Viora.Domain.Users.Owners.Owner", b =>
                        {
                            b.HasOne("Viora.Domain.Users.Identity.User", "UserProfile")
                                .WithOne()
                                .HasForeignKey("Viora.Domain.Users.Owners.Owner", "Id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.OwnsOne("Viora.Domain.Users.Internal.PersonalInfo", "PersonalInfo", b1 =>
                                {
                                    b1.Property<Guid>("OwnerId")
                                        .HasColumnType("uniqueidentifier");

                                    b1.Property<DateOnly>("DateOfBirth")
                                        .HasColumnType("date")
                                        .HasColumnName("DateOfBirth");

                                    b1.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("FirstName");

                                    b1.Property<string>("Gender")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Gender");

                                    b1.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("LastName");

                                    b1.HasKey("OwnerId");

                                    b1.ToTable("Owners");

                                    b1.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b.Navigation("PersonalInfo")
                                .IsRequired();

                            b.Navigation("UserProfile");
                        });

                    modelBuilder.Entity("Viora.Infrastructure.Authentication.LocalCredential", b =>
                        {
                            b.HasOne("Viora.Domain.Users.Identity.User", null)
                                .WithOne()
                                .HasForeignKey("Viora.Infrastructure.Authentication.LocalCredential", "UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    modelBuilder.Entity("Viora.Domain.Users.Customers.Customer", b =>
                        {
                            b.Navigation("MedicalRecord");

                            b.Navigation("OrganizationVisits");
                        });

                    modelBuilder.Entity("Viora.Domain.Users.Identity.User", b =>
                        {
                            b.Navigation("Identities");
                        });

#pragma warning restore 612, 618

        }
    }
}
