# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build using Docker Compose
        run: docker compose -f Viora/docker-compose.yml build 
